<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-10T18:05:15 IST" name="Suite" finished-at="2024-12-10T18:05:40 IST" duration-ms="24588">
    <groups>
    </groups>
    <test started-at="2024-12-10T18:05:15 IST" name="Submitorder" finished-at="2024-12-10T18:05:29 IST" duration-ms="13550">
      <class name="selenium.SeleniumFramework.Standalonetest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selenium.SeleniumFramework.Standalonetest@4082ba93]" started-at="2024-12-10T18:05:16 IST" name="launchApplication" finished-at="2024-12-10T18:05:20 IST" duration-ms="3891" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitorder(java.util.HashMap)[pri:0, instance:selenium.SeleniumFramework.Standalonetest@4082ba93]" started-at="2024-12-10T18:05:20 IST" name="submitorder" data-provider="getdata" finished-at="2024-12-10T18:05:29 IST" duration-ms="9244" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Suhani@2010, product=ZARA COAT 3, email=suhani@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitorder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:selenium.SeleniumFramework.Standalonetest@4082ba93]" started-at="2024-12-10T18:05:29 IST" name="TearDown" finished-at="2024-12-10T18:05:29 IST" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- selenium.SeleniumFramework.Standalonetest -->
    </test> <!-- Submitorder -->
    <test started-at="2024-12-10T18:05:29 IST" name="ErrorValidation" finished-at="2024-12-10T18:05:40 IST" duration-ms="10617">
      <class name="selenium.SeleniumFramework.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selenium.SeleniumFramework.ErrorValidation@50378a4]" started-at="2024-12-10T18:05:29 IST" name="launchApplication" finished-at="2024-12-10T18:05:33 IST" duration-ms="3472" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginerror(java.lang.String,java.lang.String)[pri:0, instance:selenium.SeleniumFramework.ErrorValidation@50378a4]" started-at="2024-12-10T18:05:33 IST" name="loginerror" data-provider="getdata" finished-at="2024-12-10T18:05:34 IST" duration-ms="1242" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[suhani@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Suhani@2010]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at selenium.SeleniumFramework.ErrorValidation.loginerror(ErrorValidation.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginerror -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:selenium.SeleniumFramework.ErrorValidation@50378a4]" started-at="2024-12-10T18:05:34 IST" name="TearDown" finished-at="2024-12-10T18:05:34 IST" duration-ms="88" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selenium.SeleniumFramework.ErrorValidation@50378a4]" started-at="2024-12-10T18:05:34 IST" name="launchApplication" finished-at="2024-12-10T18:05:38 IST" duration-ms="3870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginerror(java.lang.String,java.lang.String)[pri:0, instance:selenium.SeleniumFramework.ErrorValidation@50378a4]" started-at="2024-12-10T18:05:38 IST" name="loginerror" data-provider="getdata" finished-at="2024-12-10T18:05:39 IST" duration-ms="1098" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[suhani@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Suhani@2010]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at selenium.SeleniumFramework.ErrorValidation.loginerror(ErrorValidation.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginerror -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:selenium.SeleniumFramework.ErrorValidation@50378a4]" started-at="2024-12-10T18:05:40 IST" name="TearDown" finished-at="2024-12-10T18:05:40 IST" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- selenium.SeleniumFramework.ErrorValidation -->
    </test> <!-- ErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
